config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'
  get 'user/imported_files', to: 'user#imported_files'
  get 'import', to: 'import_file#import'
  post 'import', to: 'import_file#upload'
  get 'user/contacts', to: 'user#contacts'
  get 'imported_files/:id/failed_registers',
      to: 'import_file#failed_registers', as: "failed_registers"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :import_files
  has_many :contacts
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    def imported_files
      @imported_files = current_user.import_files.
                          paginate(page: params[:page], per_page: 10).
                          order('created_at DESC')
    end
  
    def contacts
      @contacts = current_user.contacts.
                    paginate(page: params[:page], per_page: 10).
                    order('name ASC')
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/contacts.html.erb
<h1>Lista de Contactos</h1>

<div class="flickr_pagination">
  <%= will_paginate @contacts, :container => false %>
</div>
<% if @contacts.empty? %>
  <div><p>Sin Contactos</p></div>
<% else %>
  <table>
    <thead>
      <tr>
        <th>Nombre Completo</th>
        <th>Fecha de Cunpleaños</th>
        <th>Teléfono</th>
        <th>Dirección</th>
        <th>T. Crédito</th>
        <th>Franquicia</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      <% @contacts.each do |contact| %>
        <tr>
          <td><%= contact.name %></td>
          <td><%= contact.birthdate.to_date.strftime("%Y %B %d") %></td>
          <td><%= contact.phone %></td>
          <td><%= contact.address %></td>
          <td><%= contact.credit_card %></td>
          <td><%= contact.franchise %></td>
          <td><%= contact.email %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @contacts, :container => false %>
</div>

app/views/user/imported_files.html.erb
<h1>Imported Files</h1>

<div class="flickr_pagination">
  <%= will_paginate @imported_files, :container => false %>
</div>
<% if @imported_files.empty? %>
  <div><p>No se ha subido archivos</p></div>
<% else %>
  <table>
    <thead>
      <tr>
        <th>Nombre del archivo</th>
        <th>Archivo creado en: </th>
        <th>Estado</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @imported_files.each do |import| %>
        <tr>
          <td><%= import.file.filename.to_s %></td>
          <td><%= import.created_at %></td>
          <td><%= import.status %></td>
          <% if import.failed_registers.empty? %>
            <td>Sin errores</td>
          <% else %>
            <td><%= link_to 'Failed registers', failed_registers_path(import) %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @imported_files, :container => false %>
</div>